name: apiverve_domainexpiration
description: Domain Expiration Checker is a simple tool for checking the expiration date and age of a domain. It returns the expiration date and age of the domain provided.
version: 1.1.14
homepage: https://domainexpiration.apiverve.com?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/domainexpiration-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
